######################################################################
# Automatically generated by qmake (2.01a) jeu. mars 14 10:15:26 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . ardoise
INCLUDEPATH += . ardoise

# Input
HEADERS += ardoise/Navigateur.h
SOURCES += ardoise/main.cpp ardoise/Navigateur.cpp
