######################################################################
# Automatically generated by qmake (2.01a) jeu. mars 14 10:21:25 2013
######################################################################
QT += webkit
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Navigateur.h
SOURCES += main.cpp Navigateur.cpp
